# Generated by Django 4.2.1 on 2023-06-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_alter_tag_options_alter_scope_articles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scope",
            name="is_main",
            field=models.BooleanField(verbose_name="Основной раздел"),
        ),
    ]
